### ISSUE TITLE
FreeBSD: man page build error

### ISSUE THREAD

**Issue by nunotexbsd** [jgehring/rsvndump#21]
Hello,

Commit https://github.com/jgehring/rsvndump/commit/71d472915e98c1e8accf8f8d6513244675fa3528 is generating a build error on FreeBSD:

```
Making all in doc
--- rsvndump.xml ---
/usr/local/bin/asciidoc -b docbook -d manpage -a version=0.6.2 -o rsvndump.xml
asciidoc: No source file specified

Man page:     asciidoc --help manpage
Syntax:       asciidoc --help syntax
*** [rsvndump.xml] Error code 1
```

Thanks

**Comment by hartwork** [comment]
Hi @nunotexbsd,

I do not have access to FreeBSD. Right now I can say two things:

One, it seems to work fine with GNU make on Linux for the latest release 0.6.2 that includes mentioned commit 71d472915e98c1e8accf8f8d6513244675fa3528:
```bash
cd "$(mktemp -d)"
wget https://github.com/jgehring/rsvndump/archive/refs/tags/rsvndump-0.6.2.tar.gz
tar xf rsvndump-0.6.2.tar.gz 
cd rsvndump-rsvndump-0.6.2/
./autogen.sh 
./configure --enable-man
make -C doc/ rsvndump.xml
```

Two, file [`doc/Makefile.am`](https://github.com/jgehring/rsvndump/blob/main/doc/Makefile.am) has a part…

https://github.com/jgehring/rsvndump/blob/e6977f3a16541b0e08ad7264aea92583472dcac1/doc/Makefile.am#L3-L4

…where your output above seems to indicate that variable `$<` on the very right is not filled at all or filled with empty or something.

Which precise flavor and version of make are you running, and does it understand `$<`?

A pull request would be great, the [Linux CI](https://github.com/jgehring/rsvndump/blob/main/.github/workflows/build_and_test.yaml) will help ensure the patched version still works with GNU make on Linux. Any chance?

**Comment by nunotexbsd** [comment]
@hartwork 

FreeBSD [port](https://www.freshports.org/devel/rsvndump/) was using BSD [make](https://man.freebsd.org/cgi/man.cgi?query=make&apropos=0&sektion=0&manpath=FreeBSD+13.2-RELEASE+and+Ports&arch=default&format=html) and it seems that it doesn't support it.

Thanks

Build fixed with gmake (GNU version of 'make' utility).
